name: Package Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Change directory to react-metronome
        run: cd react-metronome

      - name: Install dependencies
        run: npm ci
        working-directory: react-metronome

      - name: Check for code changes
        id: changes
        run: |
          if [ "$(git diff --name-only HEAD^ HEAD)" ]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi
        working-directory: react-metronome

      - name: Create changeset
        if: env.changes_detected == 'true'
        run: npx changeset add
        working-directory: react-metronome

      - name: Create release version
        if: env.changes_detected == 'true'
        run: npx changeset version
        working-directory: react-metronome

      - name: Push changes and tags
        if: env.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Version Packages"
          git push origin HEAD:main --follow-tags
        working-directory: react-metronome

      - name: Publish to npm
        if: env.changes_detected == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish
        working-directory: react-metronome
